// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"HIME_PreTitleEvents","status":true,"description":"Build your own sequence of events that should occur before\r\nthe title screen begins","parameters":{"Pre-Title Map ID":"27","Use As Title":"false"}}
];
